module.exports = [
  {
    name: 'Rainbow Spiral',
    img: '/images/photos/IMG_2744 Medium',
    size: 'Large',
    style: 'T-Shirt',
    price: 20,
    tags: ['Blue', 'Black', 'Spiral'],
    archive: false,
  },
  {
    name: 'Purple Mandala',
    img: '/images/photos/IMG_2742 Medium.jpeg',
    size: 'Large',
    style: 'T-Shirt',
    price: 20,
    tags: ['Green', 'Purple', 'Mandala'],
    archive: false,
  },
  {
    name: 'Turquoise Eye',
    img: '/images/photos/IMG_2746 Medium.jpeg',
    size: 'Medium',
    style: 'T-Shirt',
    price: 20,
    tags: ['Turquoise', 'Eye'],
    archive: false,
  },
  {
    name: 'Yellow Spiral',
    img: '/images/photos/IMG_2745 Medium.jpeg',
    size: 'Medium',
    style: 'V Neck Shirt',
    price: 20,
    tags: ['Pink', 'Black', 'Spiral'],
    archive: false,
  },
]
