module.exports = [
  // {
  //   name: 'Rainbow Spiral',
  //   img: '/images/photos/Spiral.jpeg',
  //   size: 'Large',
  //   style: 'Spiral',
  //   price: 20,
  //   tags: ['Blue', 'Black', 'Spiral'],
  //   archive: false,
  // },
  // {
  //   name: 'Purple Mandala',
  //   img: '/images/photos/Mandala.jpeg',
  //   size: 'Large',
  //   style: 'Mandala',
  //   price: 20,
  //   tags: ['Green', 'Purple', 'Mandala'],
  //   archive: false,
  // },
  {
    name: 'Turquoise Eye',
    img: '/images/photos/IMG_2746 Medium.jpeg',
    size: 'Medium',
    style: 'Spiral',
    price: 20,
    tags: ['Turquoise', 'Eye'],
    archive: false,
  },
  {
    name: 'Pink Spiral',
    img: '/images/photos/IMG_2745 Medium.jpeg',
    size: 'Medium',
    style: 'Spiral',
    price: 20,
    tags: ['Pink', 'Black', 'Spiral'],
    archive: false,
  },
]
